// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20251124181641_added_construction_imotbg")]
    partial class added_construction_imotbg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataLayer.Models.CampaignAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CampaignEmailId")
                        .HasColumnType("int");

                    b.Property<string>("CampaignId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Client")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Formats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Optimization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignEmailId");

                    b.ToTable("CampaignAssets");
                });

            modelBuilder.Entity("DataLayer.Models.CampaignClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CampaignClients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Menta Peshtera"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Peshterska rakia"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Alaska"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Flirt"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kailushka"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mastika Peshtera"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Slivenska perla"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Black Ram"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Sixth Sense Gin"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Straldjanska"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Abopharma"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Citroen"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Peugeot"
                        },
                        new
                        {
                            Id = 14,
                            Name = "KiaMotors"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Italia Motors"
                        },
                        new
                        {
                            Id = 16,
                            Name = "SFA Sofia 1"
                        },
                        new
                        {
                            Id = 17,
                            Name = "SFA Sofia 2"
                        },
                        new
                        {
                            Id = 18,
                            Name = "SFA Sofia 3"
                        },
                        new
                        {
                            Id = 19,
                            Name = "SFA Sofia 4"
                        },
                        new
                        {
                            Id = 20,
                            Name = "SFA Ruse"
                        },
                        new
                        {
                            Id = 21,
                            Name = "SFA VTurnovo"
                        },
                        new
                        {
                            Id = 22,
                            Name = "SFA Okazion"
                        },
                        new
                        {
                            Id = 23,
                            Name = "SFA"
                        },
                        new
                        {
                            Id = 24,
                            Name = "SFA Broker"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Subaru"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Smart Electric Tech"
                        },
                        new
                        {
                            Id = 28,
                            Name = "HMD"
                        },
                        new
                        {
                            Id = 29,
                            Name = "MagicalFlowersBG"
                        },
                        new
                        {
                            Id = 30,
                            Name = "eBay"
                        },
                        new
                        {
                            Id = 31,
                            Name = "OraSi Bulgaria"
                        },
                        new
                        {
                            Id = 32,
                            Name = "FIZI Publishing"
                        },
                        new
                        {
                            Id = 33,
                            Name = "EMSE Publishing"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Melitta"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Pitagor School"
                        },
                        new
                        {
                            Id = 36,
                            Name = "AYA Estate"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.CampaignClientPlatform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<double>("PercentFee")
                        .HasColumnType("float");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PlatformId");

                    b.ToTable("CampaignClientPlatforms");
                });

            modelBuilder.Entity("DataLayer.Models.CampaignEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Body")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CampaignId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmailStatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CampaignEmails");
                });

            modelBuilder.Entity("DataLayer.Models.CampaignPlatform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostPerPostEngagment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CampaignPlatforms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Google"
                        },
                        new
                        {
                            Id = 2,
                            Name = "EasyAds"
                        },
                        new
                        {
                            Id = 3,
                            Name = "YouTube"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Netinfo"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Influencer marketing"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Facebook"
                        },
                        new
                        {
                            Id = 7,
                            Name = "TikTok"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Instagram"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Facebook & Instagram"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.CampaignSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CampaignSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "LastDateTimeReadEmails",
                            Value = "2025-08-08-08-00-00-0"
                        },
                        new
                        {
                            Id = 2,
                            Name = "AttachmentPath",
                            Value = "C:\\NoniApp\\WorkHardNoni\\Attachments"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ErrorFilePth",
                            Value = "C:\\NoniApp\\WorkHardNoni\\logs\\Errors.txt"
                        },
                        new
                        {
                            Id = 4,
                            Name = "SavingAttachmentsPath",
                            Value = "C:\\NoniApp\\WorkHardNoni\\Attachments"
                        },
                        new
                        {
                            Id = 5,
                            Name = "CredentialsPath",
                            Value = "C:\\Users\\Nikolay Petkov\\source\\repos\\HomeService\\CredentialsToken\\WorkHardNoniEmail\\credentials.json"
                        },
                        new
                        {
                            Id = 6,
                            Name = "MetaAccessToken",
                            Value = ""
                        },
                        new
                        {
                            Id = 7,
                            Name = "FirstClientsPage",
                            Value = "https://graph.facebook.com/v23.0/2865723520304947/adaccounts?fields=account_id,id,name&access_token=<ACCESS_TOKEN>%0A&limit=100"
                        },
                        new
                        {
                            Id = 8,
                            Name = "AccountInfomationCPC",
                            Value = "https://graph.facebook.com/v23.0/<ACCOUNT_ID>/insights?fields=campaign_id,campaign_name,cpc,objective,actions,spend&breakdowns=publisher_platform,platform_position&date_preset=last_90d&level=campaign&access_token=<ACCESS_TOKEN>"
                        },
                        new
                        {
                            Id = 9,
                            Name = "LastDateTimeKPIResult",
                            Value = "2025-08-08-08-00-00-0"
                        },
                        new
                        {
                            Id = 10,
                            Name = "GoogleAuth2TokenResposnse",
                            Value = "C:\\Users\\Nikolay Petkov\\source\\repos\\HomeService\\HomeService\\bin\\Debug\\net9.0\\token.json\\Google.Apis.Auth.OAuth2.Responses.TokenResponse-user\\Google.Apis.Auth.OAuth2.Responses.TokenResponse-user"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Common.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "LogsPath",
                            Value = "C:\\HomeService\\Logs"
                        },
                        new
                        {
                            Id = 2,
                            Name = "NgrokDNS",
                            Value = ""
                        },
                        new
                        {
                            Id = 3,
                            Name = "PortHTTP",
                            Value = ""
                        },
                        new
                        {
                            Id = 4,
                            Name = "PortHTTPs",
                            Value = ""
                        },
                        new
                        {
                            Id = 5,
                            Name = "PortId",
                            Value = ""
                        },
                        new
                        {
                            Id = 6,
                            Name = "NotificationOAuth2Token",
                            Value = ""
                        },
                        new
                        {
                            Id = 7,
                            Name = "NotificationJSONFilePath",
                            Value = "C:\\HomeService\\Files\\Notifications.json"
                        },
                        new
                        {
                            Id = 8,
                            Name = "NotificationUrl",
                            Value = "https://fcm.googleapis.com/v1/projects/medsestri-bg/messages:send"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.ImotBg.ImotBgApartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApartmentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Construction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Floor")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("MoreInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Neighbour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<double?>("PricePerSqMetre")
                        .HasColumnType("float");

                    b.Property<double>("SquareMetres")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImotBgApartments");
                });

            modelBuilder.Entity("DataLayer.Models.ImotBg.ImotBgSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImotBgSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SerachNeighbour",
                            Value = "mladost-1,mladost-2"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SerachCity",
                            Value = "sofiya"
                        },
                        new
                        {
                            Id = 3,
                            Name = "BaseURL",
                            Value = "https://www.imot.bg/obiavi/prodazhbi/grad-#CITY#/#CURRENTNEIGHBOURHOOD#/#CONSTRUCTION#"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.MedSestriBloodTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BngPrice")
                        .HasColumnType("float");

                    b.Property<double>("EuroPrice")
                        .HasColumnType("float");

                    b.Property<bool>("HasPriority")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MedSestriBloodTests");

                    b.HasData(
                        new
                        {
                            Id = 999,
                            BngPrice = 0.0,
                            EuroPrice = 0.0,
                            HasPriority = true,
                            Name = "НЗОК"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.MedSestriCatheter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOverdue")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MedSestriCatheters");
                });

            modelBuilder.Entity("DataLayer.Models.MedSestriPatient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("EGN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MedSestriPatients");
                });

            modelBuilder.Entity("DataLayer.Models.MedSestriPatientBloodTest", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("BloodTestId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("PatientId", "BloodTestId");

                    b.HasIndex("BloodTestId");

                    b.ToTable("MedSestriPatientsBloodTests");
                });

            modelBuilder.Entity("DataLayer.Models.CampaignAsset", b =>
                {
                    b.HasOne("DataLayer.Models.CampaignEmail", null)
                        .WithMany("Assets")
                        .HasForeignKey("CampaignEmailId");
                });

            modelBuilder.Entity("DataLayer.Models.CampaignClientPlatform", b =>
                {
                    b.HasOne("DataLayer.Models.CampaignClient", "Client")
                        .WithMany("ClientPlatforms")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.CampaignPlatform", "Platform")
                        .WithMany("ClientPlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("DataLayer.Models.MedSestriPatientBloodTest", b =>
                {
                    b.HasOne("DataLayer.Models.MedSestriBloodTest", "BloodTest")
                        .WithMany("PatientBloodTests")
                        .HasForeignKey("BloodTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.MedSestriPatient", "Patient")
                        .WithMany("PatientBloodTests")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodTest");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DataLayer.Models.CampaignClient", b =>
                {
                    b.Navigation("ClientPlatforms");
                });

            modelBuilder.Entity("DataLayer.Models.CampaignEmail", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("DataLayer.Models.CampaignPlatform", b =>
                {
                    b.Navigation("ClientPlatforms");
                });

            modelBuilder.Entity("DataLayer.Models.MedSestriBloodTest", b =>
                {
                    b.Navigation("PatientBloodTests");
                });

            modelBuilder.Entity("DataLayer.Models.MedSestriPatient", b =>
                {
                    b.Navigation("PatientBloodTests");
                });
#pragma warning restore 612, 618
        }
    }
}
