// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace DataLayer.CompiledModels
{
    public partial class DataBaseContextModel
    {
        private DataBaseContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("f20bae11-dbf1-4959-96ec-266940d3bc2a"), entityTypeCount: 14)
        {
        }

        partial void Initialize()
        {
            var campaignAsset = CampaignAssetEntityType.Create(this);
            var campaignClient = CampaignClientEntityType.Create(this);
            var campaignClientPlatform = CampaignClientPlatformEntityType.Create(this);
            var campaignEmail = CampaignEmailEntityType.Create(this);
            var campaignPlatform = CampaignPlatformEntityType.Create(this);
            var campaignSettings = CampaignSettingsEntityType.Create(this);
            var settings = SettingsEntityType.Create(this);
            var imotBgApartment = ImotBgApartmentEntityType.Create(this);
            var imotBgSettings = ImotBgSettingsEntityType.Create(this);
            var imotBgStatistic = ImotBgStatisticEntityType.Create(this);
            var medSestriBloodTest = MedSestriBloodTestEntityType.Create(this);
            var medSestriCatheter = MedSestriCatheterEntityType.Create(this);
            var medSestriPatient = MedSestriPatientEntityType.Create(this);
            var medSestriPatientBloodTest = MedSestriPatientBloodTestEntityType.Create(this);

            CampaignAssetEntityType.CreateForeignKey1(campaignAsset, campaignEmail);
            CampaignClientPlatformEntityType.CreateForeignKey1(campaignClientPlatform, campaignClient);
            CampaignClientPlatformEntityType.CreateForeignKey2(campaignClientPlatform, campaignPlatform);
            MedSestriPatientBloodTestEntityType.CreateForeignKey1(medSestriPatientBloodTest, medSestriBloodTest);
            MedSestriPatientBloodTestEntityType.CreateForeignKey2(medSestriPatientBloodTest, medSestriPatient);

            CampaignAssetEntityType.CreateAnnotations(campaignAsset);
            CampaignClientEntityType.CreateAnnotations(campaignClient);
            CampaignClientPlatformEntityType.CreateAnnotations(campaignClientPlatform);
            CampaignEmailEntityType.CreateAnnotations(campaignEmail);
            CampaignPlatformEntityType.CreateAnnotations(campaignPlatform);
            CampaignSettingsEntityType.CreateAnnotations(campaignSettings);
            SettingsEntityType.CreateAnnotations(settings);
            ImotBgApartmentEntityType.CreateAnnotations(imotBgApartment);
            ImotBgSettingsEntityType.CreateAnnotations(imotBgSettings);
            ImotBgStatisticEntityType.CreateAnnotations(imotBgStatistic);
            MedSestriBloodTestEntityType.CreateAnnotations(medSestriBloodTest);
            MedSestriCatheterEntityType.CreateAnnotations(medSestriCatheter);
            MedSestriPatientEntityType.CreateAnnotations(medSestriPatient);
            MedSestriPatientBloodTestEntityType.CreateAnnotations(medSestriPatientBloodTest);

            AddAnnotation("ProductVersion", "9.0.8");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
