// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using DataLayer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace DataLayer.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class MedSestriPatientBloodTestEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "DataLayer.Models.MedSestriPatientBloodTest",
                typeof(MedSestriPatientBloodTest),
                baseEntityType,
                propertyCount: 2,
                navigationCount: 2,
                foreignKeyCount: 2,
                unnamedIndexCount: 1,
                keyCount: 1);

            var patientId = runtimeEntityType.AddProperty(
                "PatientId",
                typeof(int),
                propertyInfo: typeof(MedSestriPatientBloodTest).GetProperty("PatientId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MedSestriPatientBloodTest).GetField("<PatientId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            patientId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var bloodTestId = runtimeEntityType.AddProperty(
                "BloodTestId",
                typeof(int),
                propertyInfo: typeof(MedSestriPatientBloodTest).GetProperty("BloodTestId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MedSestriPatientBloodTest).GetField("<BloodTestId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            bloodTestId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { patientId, bloodTestId });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { bloodTestId });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("BloodTestId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            var bloodTest = declaringEntityType.AddNavigation("BloodTest",
                runtimeForeignKey,
                onDependent: true,
                typeof(MedSestriBloodTest),
                propertyInfo: typeof(MedSestriPatientBloodTest).GetProperty("BloodTest", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MedSestriPatientBloodTest).GetField("<BloodTest>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var patientBloodTests = principalEntityType.AddNavigation("PatientBloodTests",
                runtimeForeignKey,
                onDependent: false,
                typeof(List<MedSestriPatientBloodTest>),
                propertyInfo: typeof(MedSestriBloodTest).GetProperty("PatientBloodTests", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MedSestriBloodTest).GetField("<PatientBloodTests>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("PatientId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            var patient = declaringEntityType.AddNavigation("Patient",
                runtimeForeignKey,
                onDependent: true,
                typeof(MedSestriPatient),
                propertyInfo: typeof(MedSestriPatientBloodTest).GetProperty("Patient", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MedSestriPatientBloodTest).GetField("<Patient>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var patientBloodTests = principalEntityType.AddNavigation("PatientBloodTests",
                runtimeForeignKey,
                onDependent: false,
                typeof(List<MedSestriPatientBloodTest>),
                propertyInfo: typeof(MedSestriPatient).GetProperty("PatientBloodTests", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MedSestriPatient).GetField("<PatientBloodTests>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "MedSestriPatientsBloodTests");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
